### ISSUE TITLE
Undefined symbol: SHA512

### ISSUE THREAD

**Issue by MaggieNgWu** [bigchaindb/js-bigchaindb-driver#133]
### Environment
OS: Ubuntu 14.04 TLS
node: v8.9.2
npm: 5.6.0
bigchaindb-driver: 3.2.0
Electron: 1.7.10
Electron-rebuild: 1.6.0

### Error
I use Bigchaindb-driver in my [Electron](https://electronjs.org/) application.
```
const driver = require('bigchaindb-driver')
const API_PATH = 'http://localhost:9984/api/v1/';
var zila={
		"publicKey": "QhLyduKhqNSaR8e27BzNAsU8hBZzrDEi82t2t34HGfx",
  		"privateKey": "DuvuQjGH6AdKiKyFh6rgx1wBENkuHEUnLxmCfjysPMk5" 
	}
var conn = new driver.Connection(API_PATH);
const assetdata = {
	'test':{
		'serial_number':'dds=26373',
		'manufacturer':'car Tech Inc.'
	},
	'BBset':{
		'manufacturer':'car Tech Inc.'
	}
}

const metadata = { 'planet':'earth'}

try {
	//Asset creation
	const txCreateZilaSimple = driver.Transaction.makeCreateTransaction(
		assetdata,
		metadata,
		[driver.Transaction.makeOutput(
			driver.Transaction.makeEd25519Condition(zila.publicKey))],
		zila.publicKey
	)
	var txCreateZilaSimpleSigned = driver.Transaction.signTransaction(txCreateZilaSimple, zila.privateKey) //Throw Error.
	conn.postTransaction(txCreateZilaSimpleSigned)
	.then(() => conn.pollStatusAndFetchTransaction(txCreateZilaSimpleSigned.id))
	.then(retrievedTx => console.log('Transaction', retrievedTx.id, 'successfully posted.'))

} catch (err) {
	console.log(err);
}
```
I get an error below: Undefined symbol SHA512
```
$ npm start

> DataTradingDemo@1.3.0 start /home/maggie/Workspace/FirstElectron
> electron .

/home/maggie/Workspace/FirstElectron/node_modules/electron/dist/electron --type=renderer --no-sandbox --primordial-pipe-token=214DB30BF7D0AB30478D6635DEE883B6 --lang=en-US --app-path=/home/maggie/Workspace/FirstElectron --node-integration=true --webview-tag=true --no-sandbox --enable-pinch --num-raster-threads=2 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553 --disable-accelerated-video-decode --service-request-channel-token=214DB30BF7D0AB30478D6635DEE883B6 --renderer-client-id=4 --shared-files=v8_natives_data:100,v8_snapshot_data:101: symbol lookup error: /home/maggie/Workspace/FirstElectron/node_modules/ed25519/build/Release/ed25519.node: undefined symbol: SHA512
/home/maggie/Workspace/FirstElectron/node_modules/electron/dist/electron .: symbol lookup error: /home/maggie/Workspace/FirstElectron/node_modules/ed25519/build/Release/ed25519.node: undefined symbol: SHA512
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! DataTradingDemo@1.3.0 start: `electron .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the DataTradingDemo@1.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/maggie/.npm/_logs/2017-12-21T09_21_32_798Z-debug.log
```
The content in /home/maggie/.npm/_logs/2017-12-21T09_21_32_798Z-debug.log is:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle DataTradingDemo@1.3.0~prestart: DataTradingDemo@1.3.0
6 info lifecycle DataTradingDemo@1.3.0~start: DataTradingDemo@1.3.0
7 verbose lifecycle DataTradingDemo@1.3.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle DataTradingDemo@1.3.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/maggie/Workspace/FirstElectron/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin
9 verbose lifecycle DataTradingDemo@1.3.0~start: CWD: /home/maggie/Workspace/FirstElectron
10 silly lifecycle DataTradingDemo@1.3.0~start: Args: [ '-c', 'electron .' ]
11 info lifecycle DataTradingDemo@1.3.0~start: Failed to exec start script
12 verbose stack Error: DataTradingDemo@1.3.0 start: `electron .`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at ChildProcess.emit (events.js:214:7)
12 verbose stack     at maybeClose (internal/child_process.js:925:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
13 verbose pkgid DataTradingDemo@1.3.0
14 verbose cwd /home/maggie/Workspace/FirstElectron
15 verbose Linux 3.13.0-123-generic
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
17 verbose node v8.9.2
18 verbose npm  v5.6.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error DataTradingDemo@1.3.0 start: `electron .`
23 error spawn ENOENT
24 error Failed at the DataTradingDemo@1.3.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by MaggieNgWu** [comment]
Anyone has any idea?

**Comment by manolodewiner** [comment]
I saw that you solved the problem [electron/issues/11497](https://github.com/electron/electron/issues/11497#issuecomment-353322415)
Can we close this issue then?
