### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined while using function driver.Transaction.makeTransferTransaction()

### ISSUE THREAD

**Issue by rahul70392** [bigchaindb/js-bigchaindb-driver#150]
Below is my code in nodejs. 

```javascript
const driver = require('bigchaindb-driver')

let conn = new driver.Connection('https://test.bigchaindb.com/api/v1/', {
    app_id: 'b386ae44',
    app_key: '4ea69bbf5a7edd5f31760825a5dfd8c9'
})

const alice = new driver.Ed25519Keypair()
const bob = new driver.Ed25519Keypair()

console.log('Alice: ', alice.publicKey)
console.log('Bob: ', bob.publicKey)

// Define the asset to store, in this example
// we store a bicycle with its serial number and manufacturer
const assetdata = {
        'bicycle': {
                'serial_number': 'cde',
                'manufacturer': 'Bicycle Inc.',
        }
}

const metadata = {'planet': 'earth'}

// Construct a transaction payload
const txCreateAliceSimple = driver.Transaction.makeCreateTransaction(
        assetdata,
        metadata,

        [ driver.Transaction.makeOutput(
                        driver.Transaction.makeEd25519Condition(alice.publicKey))
        ],
        alice.publicKey
)

// Sign the transaction with private keys of Alice to fulfill it
const txCreateAliceSimpleSigned = driver.Transaction.signTransaction(txCreateAliceSimple, alice.privateKey)

conn.postTransaction(txCreateAliceSimpleSigned)

        .then(() => conn.pollStatusAndFetchTransaction(txCreateAliceSimpleSigned.id))
        .then(retrievedTx => console.log('Transaction', retrievedTx.id, 'successfully posted.'))
        .then(() => conn.getStatus(txCreateAliceSimpleSigned.id))
        .then(status => console.log('Retrieved status method 2: ', status))

        // Transfer bicycle to Bob
        .then(() => {
                const txTransferBob = driver.Transaction.makeTransferTransaction(
                        // signedTx to transfer and output index
                        [{ tx: txCreateAliceSimpleSigned, output_index: 0 }],
                        [driver.Transaction.makeOutput(driver.Transaction.makeEd25519Condition(bob.publicKey))],
                        // metadata
                        {price: '100 euro'}
                )

                // Sign with alice's private key
                let txTransferBobSigned = driver.Transaction.signTransaction(txTransferBob, alice.privateKey)
                console.log('Posting signed transaction: ', txTransferBobSigned)

                // Post and poll status
                return conn.postTransaction(txTransferBobSigned)
        })
        .then(res => {
                console.log('Response from BDB server:', res)
                return conn.pollStatusAndFetchTransaction(res.id)
        })
        .catch(err => {
            console.log("err",err)
        })
```

I am getting an error as below : 

 Cannot read property 'id' of undefined
    at Object.makeTransferTransaction (/Users/rahul703/Desktop/Projects/bigChain/node_modules/bigchaindb-driver/dist/node/transaction/makeTransferTransaction.js:56:108)
    at conn.postTransaction.then.then.then.then.then (/Users/rahul703/Desktop/Projects/bigChain/test2.js:61:58)
    at tryCatch (/Users/rahul703/Desktop/Projects/bigChain/node_modules/es6-promise/dist/es6-promise.js:409:12)
    at invokeCallback (/Users/rahul703/Desktop/Projects/bigChain/node_modules/es6-promise/dist/es6-promise.js:424:13)
    at publish (/Users/rahul703/Desktop/Projects/bigChain/node_modules/es6-promise/dist/es6-promise.js:398:7)
    at flush (/Users/rahul703/Desktop/Projects/bigChain/node_modules/es6-promise/dist/es6-promise.js:128:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by manolodewiner** [comment]
I am afraid you are using the old version of the Driver.
Please update it, just do:
```
npm install -s bigchaindb-driver
```

**Comment by rahul70392** [comment]
It works. Thanks a lot.
