### ISSUE TITLE
driver.Transaction.delegateSignTransaction is not a function gives error  on my local setup

### ISSUE THREAD

**Issue by amiranviam** [bigchaindb/js-bigchaindb-driver#306]
Everything works fine when I use test.io online server but when tried same code on my local setup of bigchaindb it gives me error

 
const txSigned1 = driver.Transaction.delegateSignTransaction(tx, signTransaction())
                                     ^

TypeError: driver.Transaction.delegateSignTransaction is not a function
    at Object.<anonymous> (C:\Users\acer\first-app\bigchaindb.js:101:38)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)[39m
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)[39m
    at Module.load (internal/modules/cjs/loader.js:996:32)[39m
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)[39m
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
    at internal/main/run_main_module.js:17:47[39m

**Comment by DkReactNative** [comment]
Could you send me more detail and code

**Comment by getlarge** [comment]
@amiranviam  `delegateSignTransaction` has been implemented not long ago and the driver has not been published to npm since.

**Comment by getlarge** [comment]
@amiranviam A new release has been made which will allow you to use ` delegateSignTransaction`.
